# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: fhir.org.nz.ig.northernregion
canonical: http://fhir.org.nz/ig/northernregion
version: 0.2.0
name: NorthernRegionIG
title: Northern Region Implementation Guide
status: active
publisher:
  name: healthAlliance
  email: mailto:david.hay25@gmail.com
description: The work being done for the Northern Region under healthAlliance.
license: CC0-1.0
fhirVersion: 4.0.1
dependencies:
  #fhir.org.nz.ig.base: 1.0.0
  fhir.org.nz.ig.base: current
  
parameters:
  show-inherited-invariants: false
copyrightYear: 2020+
releaseLabel: CI Build

# ╭─────────────────────────────────────────────ig.ini─────────────────────────────────────────────╮
# │  To use a provided ig-data/ig.ini file, delete the "template" property below.                  │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
# template: fhir.base.template#current
# template: haTemplate temp


# ╭────────────────────────────────────────────menu.xml────────────────────────────────────────────╮
# │  To control the menu.xml using this config, uncomment and set the "menu" property.             │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
menu:
    Home: index.html
    Use cases: usecases.html
    # Design : design.html
    Profiles: profiles.html
    Extensions: extensions.html
    # Terminology: terminology.html
    # API: CapabilityStatement.html
    # Examples: examples.html
    # API: 
    #  Documentation: api.html
    #   CapabilityStatement: CapabilityStatement.html
    Artifact index: artifacts.html
    Support:
        # Companion: companion.html
        FHIR Spec: http://hl7.org/fhir/R4/index.html
        Downloads: downloads.html
    # Development: development.html

